name: scan
on:
  schedule:
    - cron: 0 8 * * *
  push:
    branches:
      - master
jobs:
  scan:
    strategy:
      matrix:
        image:
          - '{"name": "docker.io/tmtde/osrm-backend-volume:latest", "ignore_unfixed": true}'
          - '{"name": "docker.io/tmtde/osrm-backend-volume:development", "ignore_unfixed": true}'
          - '{"name": "docker.io/tmtde/php72-fpm:latest", "ignore_unfixed": true}'
          - '{"name": "docker.io/tmtde/php73-fpm:latest", "ignore_unfixed": true}'
          - '{"name": "docker.io/tmtde/php73-fpm:latest", "ignore_unfixed": true}'
          - '{"name": "docker.io/tmtde/php80-fpm:latest", "ignore_unfixed": true}'

          
    runs-on: ubuntu-latest
    name: Scan
    steps:
      - name: Scan ${{ fromJSON(matrix.image.name) }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(matrix.image.name) }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: ${{ fromJSON(matrix.image.ignore_unfixed) }}
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'     
