name: scan
on:
  schedule:
    - cron: 0 8 * * *
  push:
    branches:
      - master
jobs:
  scan:
    strategy:
      matrix:
        image:
          - docker.io/tmtde/osrm-backend-volume:latest
          - docker.io/tmtde/osrm-backend-volume:development
          - docker.io/tmtde/php72-fpm:latest
          - docker.io/tmtde/php73-fpm:latest
          - docker.io/tmtde/php74-fpm:latest
          - docker.io/tmtde/php80-fpm:latest          
          
    runs-on: ubuntu-latest
    name: Scan
    steps:
      - name: Scan ${{ matrix.image }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'     
